### ISSUE TITLE
Issue with Loading .ir Files in mh_infrared: "TypeError: can't convert NoneType to int"

### ISSUE THREAD

**Issue by roshanravan** [ndrnmnk/mh_infrared#2]
Hello,
I’m encountering an issue when trying to load `.ir` files into the `mh_infrared` app for MicroHydra. Specifically, when I attempt to load a custom IR file, the app immediately displays "previous page" on the screen and does not load the file. The following error is observed: TypeError: can't convert NoneType to int

This occurs with both a full IR file containing multiple commands for an LG AC remote and a simplified version containing only the "Power" button command. The app fails to load either file and just returns to the previous screen without providing any further feedback.

### Steps Taken:
1. I created a `.ir` file containing commands for an LG AC remote, including various buttons like power, temperature adjustment, and fan speed.
2. I then extracted only the "Power" button command into a separate `.ir` file.
3. Both files were tested, but the app couldn't load either of them, consistently showing "previous page" and generating the "TypeError" message.

### Attached Files:
- **Full LG AC IR File**: This file contains the entire set of commands for the LG AC remote.
```Filetype: IR signals file
Version: 1
#
# LG AC 
#
name: POWER
type: parsed
protocol: NECext
address: 81 66 00 00
command: 81 7E 00 00
# 
name: TEMP-
type: parsed
protocol: NECext
address: 81 66 00 00
command: 8A 75 00 00
# 
name: TEMP+
type: parsed
protocol: NECext
address: 81 66 00 00
command: 85 7A 00 00
# 
name: Fan Speed
type: parsed
protocol: NECext
address: 81 66 00 00
command: 99 66 00 00
# 
name: Timer
type: parsed
protocol: NECext
address: 81 66 00 00
command: 9F 60 00 00
# 
name: MODE
type: parsed
protocol: NECext
address: 81 66 00 00
command: 9B 64 00 00
```
- **Power Button Only IR File**: This file contains only the "Power" button command.
```Filetype: IR signals file
Version: 1
# LG AC Remote - Power Button
name: POWER
type: parsed
protocol: NECext
address: 0x81660000
command: 0x817E0000
```

### Expected Behavior:
The app should correctly parse and load the IR files, allowing me to use the defined commands within the app interface.

### Actual Behavior:
The app fails to load the `.ir` files, immediately displaying "previous page" on the screen and generating the error mentioned above. It does not proceed past the loading stage.

### Additional Information:
I have tried various formats and simplifications of the IR file to match what the app might expect, but the issue persists. Any guidance on resolving this issue or adjusting the file format would be greatly appreciated.

Thank you for your support.

**Comment by ndrnmnk** [comment]
Hello! The app can open ir files only with raw signal format (for now, i'll implement NEC in a week or so). This causes app not to see any signals in file. For now, if you have ir scanner, use it to generate a file with raw format. If you don't have one, use this:

```
Version: 1
#
# LG AC, converted to raw using ChatGPT
#
name: POWER
type: raw
frequency: 38200
duty_cycle: 0.330000
data: 9000 4500 560 1690 560 560 560 560 560 560 560 560 560 1690 560 560 560 1690 560 1690 560 560 560 560 560 1690 560 1690 560 560 560 560 560 560 560 560 560 1690 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 560 560 560 560 1690 560 560 560 560 560 560 560 560 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 560 560 560 560 1690 560 1690 560 1690 560 560
#
name: TEMP-
type: raw
frequency: 38200
duty_cycle: 0.330000
data: 9000 4500 560 1690 560 560 560 560 560 560 560 560 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 1690 560 560 560 560 560 1690 560 1690 560 560 560 1690 560 1690 560 560 560 560 560 1690 560 560 560 560 560 560 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 560 560 560 560 1690 560 1690 560 1690 560 1690 560 1690 560 560 560 560 560 1690 560 1690 560 560 560 560 560 1690 560 560 560 560 560 560 560 560 560 1690 560 560 560 1690 560 560
#
name: TEMP+
type: raw
frequency: 38200
duty_cycle: 0.330000
data: 9000 4500 560 1690 560 560 560 560 560 560 560 560 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 1690 560 560 560 560 560 1690 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 560 560 560 560 560 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 1690 560 560 560 1690 560 560 560 560 560 560 560 1690 560 560 560 1690 560 560 
#
name: Fan Speed
type: raw
frequency: 38200
duty_cycle: 0.330000
data: 9000 4500 560 1690 560 560 560 560 560 560 560 560 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 1690 560 560 560 1690 560 560 560 1690 560 560 560 1690 560 1690 560 560 560 1690 560 1690 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 560 560 560 560 560 560 560 560 1690 560 560 560 1690 560 560 
#
name: Timer
type: raw
frequency: 38200
duty_cycle: 0.330000
data: 9000 4500 560 1690 560 560 560 560 560 560 560 560 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 560 560 560 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 560 560 560 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 560 560 560 560 560 560 1690 560 560 560 1690 560 560 
#
name: MODE
type: raw
frequency: 38200
duty_cycle: 0.330000
data: 9000 4500 560 1690 560 560 560 560 560 560 560 560 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 1690 560 560 560 1690 560 1690 560 560 560 1690 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 1690 560 560 560 1690 560 560 560 1690 560 1690 560 560 560 560 560 560 560 1690 560 560 560 1690 560 560 
```

**Comment by roshanravan** [comment]
Thanks! With this code, the app can now open the IR file. I assume the space key is the select button, not the Enter key? As soon as I select it with the space key, the button jumps and doesn't let me select the same button/key again. 

I also noticed that the app can't read the IR file from the SD/ir folder; I have to copy it locally next to log.txt using MicroHydra's Files app. 

One more suggestion: it would be helpful if the app could save the imported IR files so that I don't have to load the IR file again every time I open the app.

**Comment by ndrnmnk** [comment]
Both enter and space key work as select key. There is just no visual indication that signal sent signal. Indication looked ugly when i tried to implement it, so it got removed. The problem with loading files from folders or sdcard just got fixed, and i like your suggestion, will implement it later

edit: implemented loading last file
edit2: added nec support, but cant test if it works, my tv uses some other format. Please notify me if it works or not
